version: "3.9"
services:
  ref_server:
    build:
      dockerfile: src/ref_server/Dockerfile
      context: .
    ports:
      - "8080:8080"
  bus_server:
    build:
      dockerfile: src/bus_server/Dockerfile
      context: .
    ports:
      - "8000:8000"
    volumes:
      - local:/app/local
    depends_on:
      - ref_server
    environment:
      - BUS_APP_REF_SERVER_URL=http://ref_server:8080
